name: Fix PHP code style issues

on:
  workflow_dispatch: #Allow manual trigger
  push:
    paths:
      - '**.php'
      - '**.css'
      - '**.vue'

permissions:
  contents: write

jobs:
  php-code-styling:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Install NPM Dependencies
        run: npm ci

      - name: Install Composer Dependencies
        run: composer install --no-interaction

      - name: Pull changes
        run: git pull

      - name: Fix PHP code style issues
        run: composer format

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Fix styling
